[@ww.label labelKey="ruby.runtime" name="ruby"/]
[@ww.label labelKey="bundler.cli.arguments" name="arguments"/]
[@ww.label labelKey="rake.environment" name="environmentVariables"/]
[@ww.label labelKey="ruby.bundleexec" name="bundleexec"/]
[@ww.label labelKey="bundler.cli.trace" name="trace"/]
[@ww.label labelKey="rake.verbose" name="verbose"/]