[@ww.label labelKey="ruby.runtime" name="ruby"/]
[@ww.label labelKey="rake.rakefile" name="rakefile"/]
[@ww.label labelKey="rake.rakelibdir" name="rakelibdir"/]
[@ww.label labelKey="rake.targets" name="targets"/]
[@ww.label labelKey="rake.environment" name="environmentVariables"/]
[@ww.label labelKey="ruby.bundleexec" name="bundleexec"/]
[@ww.label labelKey="rake.trace" name="trace"/]
[@ww.label labelKey="rake.verbose" name="verbose"/]